---
apiVersion: v1
kind: Pod
metadata:
  name: placeholder-name
spec:
  containers:
    - image: apache/airflow:2.2.4
      imagePullPolicy: IfNotPresent
      name: base
      env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: postgresql://admin:test123@tien-test-3b2od-postgres-wt4ug6-custom-resource-service:5432/postgresdb
        - name: AIRFLOW__CORE__EXECUTOR
          value: KubernetesExecutor
      volumeMounts:
        - mountPath: "/opt/airflow/logs"
          name: logs-pv
        - mountPath: /opt/airflow/dags
          name: dags-pv
          readOnly: true
  restartPolicy: Never
  securityContext:
    runAsUser: 50000
    fsGroup: 50000
  serviceAccountName: "airflow-scheduler"
  volumes:
    - name: dags-pv 
      persistentVolumeClaim: 
        claimName: airflow-dags
    - name: logs-pv 
      persistentVolumeClaim: 
        claimName: airflow-logs
